import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const src=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
test('hero keeps أثر as one word with blinds reveal and looping video',()=>{assert.match(src,/className="hero-word"/);assert.doesNotMatch(src,/heroLetters|hero-letter/);assert.match(src,/<motion\.video[^>]*className="hero-video"[^>]*autoPlay[^>]*muted[^>]*loop/);assert.match(src,/className="blind-slice"/);});
test('sketch scene is a paper drawing animation with no caption or person photo',()=>{assert.match(src,/className="drawing-paper"/);assert.match(src,/className="draw-path"/);assert.doesNotMatch(src,/sketch-caption|realSketch/);});
test('light shadow material has a real light background',()=>{assert.match(src,/light:[^,\n]+/);assert.doesNotMatch(src,/light:''|light:null/);});
test('passage heading is normal white, not inverted',()=>{assert.match(css,/\.passage h2\{[^}]*color:#fff/);assert.match(css,/\.passage h2\{color:#fff;mix-blend-mode:normal/);});
test('fragments use requested blue',()=>{assert.match(css,/\.fragments\{[^}]*background:#084CA0/i);});
test('footer uses supplied sky and building layers with white heading',()=>{assert.match(src,/\/assets\/sky\.png/);assert.match(src,/\/assets\/building\.png/);assert.match(src,/className="end-building"/);assert.match(css,/\.end-copy h2\{[^}]*color:#fff/);});
