import React,{useEffect,useRef,useState}from"react";
import{motion,AnimatePresence,useScroll,useTransform,useMotionValueEvent,animate}from"framer-motion";
import{ArrowUpLeft,Plus,Menu,ArrowLeft}from"lucide-react";
const P=[
{name:"دار الوادي",loc:"الرياض",type:"منزل خاص",img:"https://images.unsplash.com/photo-1768200498972-fd56353d73fc?auto=format&fit=crop&w=2200&q=88"},
{name:"بيت الساحة",loc:"الدرعية",type:"منزل فناء",img:"https://images.unsplash.com/photo-1783125127257-28dbc0523a68?auto=format&fit=crop&w=2200&q=88"},
{name:"دار النور",loc:"جدة",type:"منزل ساحلي",img:"https://images.unsplash.com/photo-1775466145653-a47a853428d2?auto=format&fit=crop&w=2200&q=88"},
{name:"بيت النخيل",loc:"الرياض",type:"منزل خاص",img:"https://images.unsplash.com/photo-1760067537265-dc9f11824eda?auto=format&fit=crop&w=2200&q=88"}]
const SKETCHES=[
{label:"دراسة حركة ومسقط",img:"https://images.unsplash.com/photo-1698846296220-e44d9d4b9100?auto=format&fit=crop&w=1800&q=88"},
{label:"مسقط أولي",img:"https://images.unsplash.com/photo-1721244654210-a505a99661e9?auto=format&fit=crop&w=1800&q=88"},
{label:"واجهة ونِسَب",img:"https://images.unsplash.com/photo-1721244653693-1d13e68b66c1?auto=format&fit=crop&w=1800&q=88"},
{label:"دراسة الكتلة والموقع",img:"https://images.unsplash.com/photo-1717250264930-9e06b67f3c82?auto=format&fit=crop&w=1800&q=88"}];
function Cursor(){const[x,setX]=useState(-100),[y,setY]=useState(-100);useEffect(()=>{const m=e=>{setX(e.clientX);setY(e.clientY)};addEventListener("pointermove",m);return()=>removeEventListener("pointermove",m)},[]);return <motion.div className="cursor" animate={{x:x-12,y:y-12}} transition={{type:"spring",stiffness:500,damping:35}}/>}
function ActionButton({children,href="#",light=false}){const[x,setX]=useState(45);return <motion.a className={`actionButton ${light?"light":""}`} href={href} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setX(e.clientX-r.left)}} whileHover={{scale:1.035}} whileTap={{scale:.95}}><span>{children}</span><ArrowUpLeft/><motion.i animate={{x:x-34}} transition={{type:"spring",stiffness:160,damping:17}}/></motion.a>}
function Hero(){const ref=useRef(null);const{scrollYProgress,scrollY}=useScroll({target:ref,offset:["start start","end start"]});const scale=useTransform(scrollYProgress,[0,1],[1,1.18]);const titleY=useTransform(scrollYProgress,[0,1],[0,-140]);const[scrolled,setScrolled]=useState(false);useMotionValueEvent(scrollY,"change",v=>setScrolled(v>70));return <section ref={ref} className="Hero hero"><motion.video className="heroVideo" style={{scale}} autoPlay muted loop playsInline poster={P[0].img}><source src="https://videos.pexels.com/video-files/4301618/4301618-hd_1920_1080_30fps.mp4" type="video/mp4"/></motion.video><div className="heroShade"/><nav className={scrolled?"nav scrolled":"nav"}><b>أثَر</b><span>المشاريع　 الاستوديو　 المنهج　 تواصل</span><Menu/></nav><motion.div className="heroTitle" style={{y:titleY}}><span className="heroKicker">استوديو عمارة سكنية / الرياض</span><h1>نصمّم<br/><em>ما يبقى.</em></h1><p>نصمّم منازل خاصة في السعودية والخليج، من الفكرة الأولى حتى التفاصيل التي تُبنى وتُعاش.</p><ActionButton href="#projects">اكتشف المشاريع</ActionButton></motion.div></section>}
function Manifesto(){return <section className="Manifesto manifesto"><motion.h2 initial={{opacity:0,y:70}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.35}} transition={{duration:.85}}>نبدأ بالمكان،<br/>لا بالشكل.</motion.h2><div className="manifestCopy"><p>قبل الخط الأول نقرأ الأرض والشمس وطريقة عيش الأسرة. نربط العمارة بالداخل والحديقة والتفاصيل في فكرة واحدة، حتى يبدو المنزل امتداداً طبيعياً لموقعه وأصحابه.</p><ActionButton href="#approach">كيف نعمل</ActionButton></div></section>}
function Projects(){return <section id="projects" className="Projects projects"><header><h2>أربعة منازل.<br/>أربع شخصيات.</h2><ActionButton light href="#">عرض كل المشاريع</ActionButton></header><div className="projectJourney">{P.map((p,i)=><article className={`projectScene s${i}`} key={p.name}><div className="stickyProject"><motion.div className="projectPhoto" initial={{clipPath:"inset(10% 8%)"}} whileInView={{clipPath:"inset(0%)"}} transition={{duration:1}}><img src={p.img} alt={p.name}/><span className="coord">0{i+1} / {p.loc}</span></motion.div><motion.div className="projectWords" initial={{y:70,opacity:0}} whileInView={{y:0,opacity:1}}><h3>{p.name}</h3><p>{p.type} · {p.loc}</p></motion.div></div></article>)}</div></section>}
function MaterialStack(){const[order,setOrder]=useState([0,1,2,3]);const shuffle=()=>setOrder(o=>[o[2],o[0],o[3],o[1]]);const spread={rest:i=>({rotate:[-7,5,-3,8][i],x:[-50,28,-8,62][i],y:[35,0,58,22][i]}),spread:i=>({rotate:[-11,9,-6,12][i],x:[-145,100,-45,175][i],y:[80,-45,120,35][i],scale:1.02})};return <div className="stackArea"><motion.div className="MaterialStack stack" initial="rest" whileHover="spread" onClick={shuffle} role="button" tabIndex="0" onKeyDown={e=>(e.key==="Enter"||e.key===" ")&&shuffle()} aria-label="استكشاف اسكتشات المشروع">{order.map((n,i)=><motion.figure custom={i} variants={spread} layout key={n} animate={{zIndex:i}} transition={{type:"spring",stiffness:52,damping:18,mass:1.25}}><img src={SKETCHES[n].img} alt={SKETCHES[n].label}/><figcaption>{SKETCHES[n].label}</figcaption></motion.figure>)}</motion.div><span className="stackHint">حرّك المؤشر فوق الاسكتشات — واضغط لإعادة ترتيبها</span></div>}
function Process(){return <section className="Process process"><div><h2>نفكّر<br/>بأيدينا.</h2><p>كل منزل يبدأ على الورق: حركة الأسرة، الفناء، الضوء والخصوصية. نختبر المساقط والكتلة والمواد قبل أن تتحول الخطوط إلى مساحة حقيقية.</p><ActionButton href="#approach">اكتشف المنهج</ActionButton></div><MaterialStack/></section>}
const D=[
["العمارة السكنية",P[0].img],
["الداخل كامتداد للعمارة",P[1].img],
["التجديد والتحويل",P[2].img],
["الإشراف التصميمي",P[3].img]]
function Disciplines(){return <section className="Disciplines disciplines"><header><h2>من الكتلة<br/>إلى الملمس.</h2></header>{D.map((d,i)=><motion.article key={d[0]} whileHover="hover" initial="rest"><motion.div className="discImage" variants={{rest:{clipPath:"inset(50% 0 50% 0)",scale:1.08},hover:{clipPath:"inset(0)",scale:1}}} transition={{duration:.55}}><img src={d[1]} alt=""/></motion.div><span>0{i+1}</span><h3>{d[0]}</h3><p>قرار واحد يمتد من الموقع والكتلة إلى المادة والتفصيلة.</p><ArrowUpLeft/></motion.article>)}</section>}
function Approach(){return <section id="approach" className="Approach approach"><div className="approachIntro"><h2>من أول خط<br/>إلى آخر تفصيلة.</h2><p>نقود المشروع عبر مراحل واضحة، بحيث يعرف العميل دائماً أين نحن، وما القرار التالي، وما الذي يحتاج إلى اعتماده.</p></div><div className="steps">{[["01","نقرأ","الموقع، الأسرة، الخصوصية، المناخ والميزانية."],["02","نرسم","المسقط، الفناء، الكتلة ومسار الضوء."],["03","نفصّل","الواجهات، المواد والداخل كتجربة واحدة."],["04","نتابع","التصميم في الموقع حتى يصبح منزلاً."]].map((step,i)=><motion.div initial={{opacity:0,y:42,scale:.94}} whileInView={{opacity:1,y:0,scale:1}} viewport={{once:true,amount:.62}} transition={{type:"spring",stiffness:240,damping:15,mass:.72,delay:i*.14}} key={step[0]}><b>{step[0]}</b><h3>{step[1]}</h3><p>{step[2]}</p></motion.div>)}</div><ActionButton light href="#">تعرّف على خدماتنا</ActionButton></section>}
function Principles(){const[active,setActive]=useState(0);const items=[
{name:"الضوء",desc:"نوجّه الفتحات والفناء بحيث يتغير المنزل مع ساعات اليوم، لا مع صورة ثابتة.",img:"https://images.unsplash.com/photo-1768200498972-fd56353d73fc?auto=format&fit=crop&w=2200&q=88"},
{name:"الظل",desc:"نصمّم الظل كجزء من الراحة والخصوصية والمناخ، وكطبقة تمنح الواجهة عمقها.",img:"https://images.unsplash.com/photo-1741524915261-3969ae58000f?auto=format&fit=crop&w=2200&q=88"},
{name:"المادة",desc:"الحجر والخشب والخرسانة تُختار لما تفعله مع اللمس والحرارة والزمن، لا للعينة وحدها.",img:"https://images.unsplash.com/photo-1783125127257-28dbc0523a68?auto=format&fit=crop&w=2200&q=88"}];
return <section className="Principles principles"><div className="principlesSticky"><AnimatePresence mode="wait"><motion.img key={active} src={items[active].img} alt={items[active].name} initial={{opacity:0,scale:1.035}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:1.015}} transition={{duration:.48}}/></AnimatePresence><div className="principlesShade"/><div className="principlesIntro"><h2>ثلاثة أشياء<br/>نصمّم بها.</h2><p>ثلاثة قرارات تتكرر في كل منزل نصمّمه، وتغيّر إحساس المكان قبل أن يصل إليه الأثاث.</p></div><div className="principleList">{items.map((it,i)=><motion.button key={it.name} className={active===i?"active":""} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} onClick={()=>setActive(i)} whileHover={{x:-10}}><span>0{i+1}</span><h3>{it.name}</h3><p>{it.desc}</p></motion.button>)}</div></div></section>}
function Faq(){const[open,setOpen]=useState(null);return <section className="Faq faq"><div className="faqInner"><header><h2>أسئلة<br/>واضحة.</h2><p>إجابات مختصرة على ما يسأل عنه عملاؤنا قبل بداية المشروع.</p></header><div>{["كيف يبدأ تصميم منزل جديد؟","هل تعملون خارج الرياض؟","ما مدة مرحلة التصميم؟","هل يشمل العمل التصميم الداخلي؟"].map((q,i)=><article key={q}><button aria-expanded={open===i} onClick={()=>setOpen(open===i?null:i)}>{q}<Plus className={open===i?"turn":""}/></button><AnimatePresence>{open===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}>نبدأ بجلسة تعريف والموقع والميزانية وطريقة عيش الأسرة، ثم نحدد نطاق العمل والمراحل والمخرجات بوضوح قبل بدء التصميم.</motion.p>}</AnimatePresence></article>)}</div></div></section>}
function Footer(){return <footer className="Footer footer"><div className="footerMedia"/><div className="footerLayout"><div className="footerWords"><h2>لنبنِ شيئاً<br/>يبقى.</h2></div><div className="footerMetaTop"><b>أثَر</b><span>استوديو عمارة سكنية<br/>الرياض، المملكة العربية السعودية</span><span><a href="#projects">المشاريع</a><br/><a href="#approach">المنهج</a><br/><a href="mailto:hello@athar.studio">hello@athar.studio</a></span><small>© 2026 ATHAR STUDIO</small></div></div></footer>}
export default function App(){return <main><Cursor/><Hero/><Manifesto/><Projects/><Process/><Disciplines/><Approach/><Principles/><Faq/><Footer/></main>}
