import React,{useRef,useState}from"react";
import{motion,AnimatePresence,useScroll,useTransform,useMotionValueEvent,animate}from"framer-motion";
import{ArrowUpLeft,Plus,Menu}from"lucide-react";
const P=[
{name:"دار الوادي",loc:"الرياض",type:"سكن خاص",img:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=2000&q=92"},
{name:"رواق الحجر",loc:"العلا",type:"فضاء ثقافي",img:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=2000&q=92"},
{name:"بيت البحر",loc:"جدة / البحر الأحمر",type:"ضيافة",img:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=2000&q=92"},
{name:"دار النخيل",loc:"الدرعية",type:"سكن خاص",img:"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=2000&q=92"}];
const MATERIALS=[
{label:"اسكتش أولي",img:"https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1500&q=90"},
{label:"حجر محلي",img:P[1].img},{label:"نموذج ضوء",img:P[0].img},{label:"تفصيل داخلي",img:P[2].img}];
function JellyButton(){const[x,setX]=useState(45);return <motion.a className="jelly" href="#projects" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setX(e.clientX-r.left)}} whileHover={{scale:1.035}} whileTap={{scale:.95}}><span>اكتشف المشاريع</span><ArrowUpLeft/><motion.i animate={{x:x-34}} transition={{type:"spring",stiffness:160,damping:17}}/></motion.a>}
function Hero(){const ref=useRef(null);const{scrollYProgress,scrollY}=useScroll({target:ref,offset:["start start","end start"]});const scale=useTransform(scrollYProgress,[0,1],[1,1.18]);const titleY=useTransform(scrollYProgress,[0,1],[0,-180]);const[scrolled,setScrolled]=useState(false);useMotionValueEvent(scrollY,"change",v=>setScrolled(v>70));return <section ref={ref} className="Hero hero"><motion.video className="heroVideo" style={{scale}} autoPlay muted loop playsInline poster={P[0].img}><source src="https://videos.pexels.com/video-files/3773486/3773486-hd_1920_1080_30fps.mp4" type="video/mp4"/></motion.video><div className="heroShade"/><motion.nav className={scrolled?"nav scrolled":"nav"} layout><b>أثَر</b><span>المشاريع　 الاستوديو　 المنهج</span><Menu/></motion.nav><motion.div className="heroTitle" style={{y:titleY}}><h1>نصمّم<br/><em>ما يبقى.</em></h1><p>عمارة تتكوّن من الضوء والمادة والسياق، لا من الشكل وحده.</p><JellyButton/></motion.div></section>}
function Manifesto(){return <section className="Manifesto manifesto"><motion.h2 initial={{clipPath:"inset(0 0 100% 0)",y:70}} whileInView={{clipPath:"inset(-8% 0 -8% 0)",y:0}} viewport={{once:true,amount:.4}} transition={{duration:.9}}>نبدأ بالمكان،<br/>لا بالشكل.</motion.h2><div className="manifestCopy"><i/><p>قبل الخط الأول نقرأ اتجاه الشمس، حركة الناس، صوت المكان، وملمس المادة. المشروع الجيد لا يبدو موضوعاً فوق أرضه؛ يبدو وكأنه كان ينتظر أن يُكتشف.</p></div></section>}
function Projects(){return <section id="projects" className="Projects projects"><header><h2>أربعة أماكن.<br/>أربع شخصيات.</h2></header><div className="projectJourney">{P.map((p,i)=><article className={`projectScene s${i}`} key={p.name}><div className="stickyProject"><motion.div className="projectPhoto" initial={{clipPath:"inset(12% 9%)"}} whileInView={{clipPath:"inset(0%)"}} transition={{duration:1}}><img src={p.img} alt={p.name}/><span className="coord">0{i+1} / {p.loc}</span></motion.div><motion.div className="projectWords" initial={{y:90,opacity:0}} whileInView={{y:0,opacity:1}}><h3>{p.name}</h3><p>{p.type}　 /　 202{6-i%2}</p></motion.div></div></article>)}</div></section>}
function MaterialStack(){const[order,setOrder]=useState([0,1,2,3]);const shuffle=()=>setOrder(o=>[o[2],o[0],o[3],o[1]]);return <div className="stackArea"><div className="MaterialStack stack" onClick={shuffle} role="button" tabIndex="0" onKeyDown={e=>(e.key==="Enter"||e.key===" ")&&shuffle()} aria-label="إعادة ترتيب عينات المواد">{order.map((n,i)=><motion.figure layout key={n} animate={{rotate:[-8,6,-3,9][i],x:[-70,30,-10,78][i],y:[45,0,72,28][i],zIndex:i}} whileHover={{y:-24,scale:1.025,zIndex:9}} transition={{type:"spring",stiffness:55,damping:18,mass:1.2}}><img src={MATERIALS[n].img} alt={MATERIALS[n].label}/><figcaption>0{n+1} / {MATERIALS[n].label}</figcaption></motion.figure>)}</div><span className="stackHint">اضغط على المجموعة لإعادة ترتيبها</span></div>}
function Process(){return <section className="Process process"><div><small>05 / MATERIAL STUDIES</small><h2>نفكّر<br/>بأيدينا.</h2><p>العينة، الاسكتش، النموذج والصورة ليست توثيقاً للعمل. هي جزء من طريقة الوصول إليه.</p></div><MaterialStack/></section>}
const D=[["العمارة",P[0].img],["التصميم الداخلي",P[2].img],["الضيافة",P[3].img],["الفضاءات الثقافية",P[1].img]];
function Disciplines(){return <section className="Disciplines disciplines"><header><small>06 / DISCIPLINES</small><h2>من الكتلة<br/>إلى الملمس.</h2></header>{D.map((d,i)=><motion.article key={d[0]} whileHover="hover" initial="rest"><motion.div className="discImage" variants={{rest:{clipPath:"inset(50% 0 50% 0)",scale:1.08},hover:{clipPath:"inset(0)",scale:1}}} transition={{duration:.55}}><img src={d[1]} alt=""/></motion.div><span>0{i+1}</span><h3>{d[0]}</h3><p>مساحات تُبنى حول الضوء، الحركة، والذاكرة.</p><ArrowUpLeft/></motion.article>)}</section>}
function AnimatedNumber({to}){const node=useRef(null);return <motion.b ref={node} onViewportEnter={()=>{const c=animate(0,to,{duration:1.8,ease:[.16,.8,.2,1],onUpdate:v=>{if(node.current)node.current.textContent=String(Math.round(v)).padStart(2,"0")}});return()=>c.stop()}}>00</motion.b>}
function Credibility(){return <section className="Credibility credibility"><h2>أقل ضجيجاً.<br/>أكثر أثراً.</h2><div className="numbers"><div><AnimatedNumber to={14}/><span>مشروعاً مختاراً</span></div><div><AnimatedNumber to={4}/><span>مدن</span></div><div><AnimatedNumber to={9}/><span>سنوات ممارسة</span></div></div></section>}
function Faq(){const[open,setOpen]=useState(null);return <section className="Faq faq"><div className="faqPhoto"/><motion.div className="faqGlass" initial={{y:80,opacity:0}} whileInView={{y:0,opacity:1}}><header><h2>أسئلة<br/>واضحة.</h2></header><div>{["كيف تبدأون مشروعاً جديداً؟","هل تعملون خارج الرياض؟","ما مدة مرحلة التصميم؟","هل تتولون التصميم الداخلي أيضاً؟"].map((q,i)=><article key={q}><button aria-expanded={open===i} onClick={()=>setOpen(open===i?null:i)}>{q}<Plus className={open===i?"turn":""}/></button><AnimatePresence>{open===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}>نبدأ بالموقع والاحتياج والميزانية، ثم نبني نطاقاً واضحاً ومراحل محددة قبل أي قرار شكلي.</motion.p>}</AnimatePresence></article>)}</div></motion.div></section>}
function Footer(){return <footer className="Footer footer"><div className="footerMedia"/><div className="footerSkyShade"/><motion.div className="footerWords" initial={{y:100,opacity:0}} whileInView={{y:0,opacity:1}}><h2>لنبنِ شيئاً<br/><em>يبقى.</em></h2><a href="mailto:hello@athar.studio">ابدأ محادثة <ArrowUpLeft/></a></motion.div><motion.div className="footerGlass" initial={{y:130}} whileInView={{y:0}}><b>أثَر</b><span>الرياض، المملكة العربية السعودية<br/>hello@athar.studio</span><span>المشاريع　الاستوديو　المنهج</span><small>© 2026 ATHAR</small></motion.div></footer>}
export default function App(){return <main><Hero/><Manifesto/><Projects/><Process/><Disciplines/><Credibility/><Faq/><Footer/></main>}
