import React,{useEffect,useRef,useState}from"react";
import{motion,AnimatePresence,useScroll,useTransform,useMotionValueEvent,animate}from"framer-motion";
import{ArrowUpLeft,Plus,Menu,ArrowLeft}from"lucide-react";
const P=[
{name:"دار الوادي",loc:"الرياض",type:"سكن خاص",img:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=2000&q=92"},
{name:"رواق الحجر",loc:"العلا",type:"فضاء ثقافي",img:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=2000&q=92"},
{name:"بيت البحر",loc:"جدة / البحر الأحمر",type:"ضيافة",img:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=2000&q=92"},
{name:"دار النخيل",loc:"الدرعية",type:"سكن خاص",img:"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=2000&q=92"}];
const SKETCHES=[
{label:"دراسة حركة ومسقط",img:"https://images.unsplash.com/photo-1698846296220-e44d9d4b9100?auto=format&fit=crop&w=1800&q=88"},
{label:"مسقط أولي",img:"https://images.unsplash.com/photo-1721244654210-a505a99661e9?auto=format&fit=crop&w=1800&q=88"},
{label:"واجهة ونِسَب",img:"https://images.unsplash.com/photo-1721244653693-1d13e68b66c1?auto=format&fit=crop&w=1800&q=88"},
{label:"دراسة الكتلة والموقع",img:"https://images.unsplash.com/photo-1717250264930-9e06b67f3c82?auto=format&fit=crop&w=1800&q=88"}];
function Cursor(){const[x,setX]=useState(-100),[y,setY]=useState(-100);useEffect(()=>{const m=e=>{setX(e.clientX);setY(e.clientY)};addEventListener("pointermove",m);return()=>removeEventListener("pointermove",m)},[]);return <motion.div className="cursor" animate={{x:x-12,y:y-12}} transition={{type:"spring",stiffness:500,damping:35}}/>}
function JellyButton(){const[x,setX]=useState(45);return <motion.a className="jelly" href="#projects" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setX(e.clientX-r.left)}} whileHover={{scale:1.035}} whileTap={{scale:.95}}><span>اكتشف المشاريع</span><ArrowUpLeft/><motion.i animate={{x:x-34}} transition={{type:"spring",stiffness:160,damping:17}}/></motion.a>}
function Hero(){const ref=useRef(null);const{scrollYProgress,scrollY}=useScroll({target:ref,offset:["start start","end start"]});const scale=useTransform(scrollYProgress,[0,1],[1,1.18]);const titleY=useTransform(scrollYProgress,[0,1],[0,-140]);const[scrolled,setScrolled]=useState(false);useMotionValueEvent(scrollY,"change",v=>setScrolled(v>70));return <section ref={ref} className="Hero hero"><motion.video className="heroVideo" style={{scale}} autoPlay muted loop playsInline poster={P[0].img}><source src="https://videos.pexels.com/video-files/3773486/3773486-hd_1920_1080_30fps.mp4" type="video/mp4"/></motion.video><div className="heroShade"/><nav className={scrolled?"nav scrolled":"nav"}><b>أثَر</b><span>المشاريع　 الاستوديو　 المنهج　 اليوميات</span><Menu/></nav><motion.div className="heroTitle" style={{y:titleY}}><h1>نصمّم<br/><em>ما يبقى.</em></h1><p>عمارة تتكوّن من الضوء والمادة والسياق، لا من الشكل وحده.</p><JellyButton/></motion.div></section>}
function Manifesto(){return <section className="Manifesto manifesto"><motion.h2 initial={{opacity:0,y:70}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.35}} transition={{duration:.85}}>نبدأ بالمكان،<br/>لا بالشكل.</motion.h2><div className="manifestCopy"><p>قبل الخط الأول نقرأ اتجاه الشمس، حركة الناس، صوت المكان، وملمس المادة. المشروع الجيد لا يبدو موضوعاً فوق أرضه؛ يبدو وكأنه كان ينتظر أن يُكتشف.</p><a href="#approach">كيف نعمل <ArrowUpLeft/></a></div></section>}
function Projects(){return <section id="projects" className="Projects projects"><header><h2>أربعة أماكن.<br/>أربع شخصيات.</h2><a className="textLink" href="#">عرض كل المشاريع <ArrowUpLeft/></a></header><div className="projectJourney">{P.map((p,i)=><article className={`projectScene s${i}`} key={p.name}><div className="stickyProject"><motion.div className="projectPhoto" initial={{clipPath:"inset(10% 8%)"}} whileInView={{clipPath:"inset(0%)"}} transition={{duration:1}}><img src={p.img} alt={p.name}/><span className="coord">0{i+1} / {p.loc}</span></motion.div><motion.div className="projectWords" initial={{y:70,opacity:0}} whileInView={{y:0,opacity:1}}><h3>{p.name}</h3><p>{p.type} · {p.loc}</p></motion.div></div></article>)}</div></section>}
function MaterialStack(){const[order,setOrder]=useState([0,1,2,3]);const shuffle=()=>setOrder(o=>[o[2],o[0],o[3],o[1]]);const spread={rest:i=>({rotate:[-7,5,-3,8][i],x:[-50,28,-8,62][i],y:[35,0,58,22][i]}),spread:i=>({rotate:[-11,9,-6,12][i],x:[-145,100,-45,175][i],y:[80,-45,120,35][i],scale:1.02})};return <div className="stackArea"><motion.div className="MaterialStack stack" initial="rest" whileHover="spread" onClick={shuffle} role="button" tabIndex="0" onKeyDown={e=>(e.key==="Enter"||e.key===" ")&&shuffle()} aria-label="استكشاف اسكتشات المشروع">{order.map((n,i)=><motion.figure custom={i} variants={spread} layout key={n} animate={{zIndex:i}} transition={{type:"spring",stiffness:52,damping:18,mass:1.25}}><img src={SKETCHES[n].img} alt={SKETCHES[n].label}/><figcaption>{SKETCHES[n].label}</figcaption></motion.figure>)}</motion.div><span className="stackHint">حرّك المؤشر فوق الاسكتشات — واضغط لإعادة ترتيبها</span></div>}
function Process(){return <section className="Process process"><div><h2>نفكّر<br/>بأيدينا.</h2><p>كل مشروع يبدأ على الورق: ملاحظات سريعة، مساقط، دراسات ضوء وكتلة. ثم نختبرها بالنماذج والمواد قبل أن تتحول إلى مكان حقيقي.</p><a className="textLink" href="#approach">اكتشف المنهج <ArrowUpLeft/></a></div><MaterialStack/></section>}
const D=[["العمارة",P[0].img],["التصميم الداخلي",P[2].img],["الضيافة",P[3].img],["الفضاءات الثقافية",P[1].img]];
function Disciplines(){return <section className="Disciplines disciplines"><header><h2>من الكتلة<br/>إلى الملمس.</h2></header>{D.map((d,i)=><motion.article key={d[0]} whileHover="hover" initial="rest"><motion.div className="discImage" variants={{rest:{clipPath:"inset(50% 0 50% 0)",scale:1.08},hover:{clipPath:"inset(0)",scale:1}}} transition={{duration:.55}}><img src={d[1]} alt=""/></motion.div><span>0{i+1}</span><h3>{d[0]}</h3><p>مساحات تُبنى حول الضوء، الحركة، والذاكرة.</p><ArrowUpLeft/></motion.article>)}</section>}
function Approach(){return <section id="approach" className="Approach approach"><div className="approachIntro"><h2>من أول خط<br/>إلى آخر تفصيلة.</h2><p>نقود المشروع عبر مراحل واضحة، بحيث يعرف العميل دائماً أين نحن، وما القرار التالي، وما الذي يحتاج إلى اعتماده.</p></div><div className="steps">{[["01","اكتشاف","الموقع، البرنامج، الميزانية والطموح."],["02","تصميم","الكتلة، الحركة، الضوء والمواد."],["03","تطوير","رسومات تفصيلية وتنسيق التخصصات."],["04","تنفيذ","متابعة التصميم حتى يتحول إلى واقع."]].map((s,i)=><motion.div initial={{opacity:.25,y:30}} whileInView={{opacity:1,y:0}} viewport={{amount:.7}} key={s[0]}><b>{s[0]}</b><h3>{s[1]}</h3><p>{s[2]}</p></motion.div>)}</div><a className="outlineButton" href="#">تعرّف على خدماتنا <ArrowUpLeft/></a></section>}
function AnimatedNumber({to}){const node=useRef(null);return <motion.b ref={node} onViewportEnter={()=>{const c=animate(0,to,{duration:1.8,ease:[.16,.8,.2,1],onUpdate:v=>{if(node.current)node.current.textContent=String(Math.round(v))}});return()=>c.stop()}}>0</motion.b>}
function Credibility(){return <section className="Credibility credibility"><h2>أقل ضجيجاً.<br/>أكثر أثراً.</h2><div className="numbers"><div><AnimatedNumber to={14}/><span>مشروعاً مختاراً</span></div><div><AnimatedNumber to={4}/><span>مدن</span></div><div><AnimatedNumber to={9}/><span>سنوات ممارسة</span></div></div></section>}
function Journal(){return <section className="Journal journal"><header><div><span>من الاستوديو</span><h2>أفكار، مواد،<br/>وأماكن نراقبها.</h2></div><a className="textLink" href="#">كل اليوميات <ArrowUpLeft/></a></header><div className="journalGrid">{[["المادة","لماذا نعود إلى الحجر المحلي؟",P[1].img],["من الموقع","ضوء الغرب في بيت البحر",P[2].img],["ملاحظة","الممر ليس مساحة ضائعة",P[3].img]].map((j,i)=><a href="#" key={j[1]}><div><img src={j[2]} alt=""/><span>0{i+1}</span></div><small>{j[0]}</small><h3>{j[1]}</h3><ArrowUpLeft/></a>)}</div></section>}
function Faq(){const[open,setOpen]=useState(null);return <section className="Faq faq"><div className="faqInner"><header><h2>أسئلة<br/>واضحة.</h2><p>إجابات مختصرة على ما يسأل عنه عملاؤنا قبل بداية المشروع.</p></header><div>{["كيف تبدأون مشروعاً جديداً؟","هل تعملون خارج الرياض؟","ما مدة مرحلة التصميم؟","هل تتولون التصميم الداخلي أيضاً؟"].map((q,i)=><article key={q}><button aria-expanded={open===i} onClick={()=>setOpen(open===i?null:i)}>{q}<Plus className={open===i?"turn":""}/></button><AnimatePresence>{open===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}>نبدأ بالموقع والاحتياج والميزانية، ثم نبني نطاقاً واضحاً ومراحل محددة قبل أي قرار شكلي.</motion.p>}</AnimatePresence></article>)}</div></div></section>}
function Footer(){return <footer className="Footer footer"><div className="footerMedia"/><div className="footerWords"><h2>لنبنِ شيئاً<br/>يبقى.</h2><a className="footerCta" href="mailto:hello@athar.studio">ابدأ مشروعاً <ArrowUpLeft/></a></div><div className="footerMeta"><b>أثَر</b><span>الرياض، المملكة العربية السعودية<br/>hello@athar.studio</span><span><a href="#projects">المشاريع</a>　<a href="#approach">المنهج</a>　<a href="#">الاستوديو</a>　<a href="#">اليوميات</a></span><small>© 2026 ATHAR STUDIO</small></div></footer>}
export default function App(){return <main><Cursor/><Hero/><Manifesto/><Projects/><Process/><Disciplines/><Approach/><Credibility/><Journal/><Faq/><Footer/></main>}
