import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AnimatePresence,motion,useScroll,useTransform} from 'framer-motion';
import './styles.css';

const IMG={
 hero:'https://mavilongevity.com/images/properties/mavi-r3-50.jpg',
 courtyard:'https://static.spacecrafted.com/fa3c03d2f10d42bfb8bfdd0889cf1089/i/e9f952ad1909484ea69dcb9385c7b0ee/1/GCuCv726gZycFxatRCb7iU/ES11.jpg',
 plan:'https://vtsland.ir/wp-content/uploads/2022/05/villa-plan-design.jpg',
 house:'https://images.divisare.com/images/f_auto%2Cq_auto%2Cw_auto/v1627307021/llnyyh02bhiawbk3cxtx/grupo-studio-gonzalo-viramonte-casa-si.jpg',
 desert:'https://morphome.app/assets/renders/concrete-desert-house.jpg',
 realSketch:'https://images.squarespace-cdn.com/content/v1/64b967a1b466013336dbb07c/1691004888274-XMIDN8DEBZF2W9J9F4RO/20180202_154015.jpg',
 light:'https://architizer-prod.imgix.net/media/mediadata/uploads/1717434565130213.JPEG?auto=format%2Ccompress&cs=strip&q=80&w=1800',
 shadow:'https://images.divisare.com/images/c_limit%2Cf_auto%2Ch_2000%2Cq_auto%2Cw_3000/v1468257182/w72llzpljwrj1rrxdjsw/bernardo-rosello-ramiro-sosa-house-in-palihue.jpg',
 material:'https://assets.zyrosite.com/cdn-cgi/image/format%3Dauto%2Cw%3D1600%2Ch%3D1600%2Cfit%3Dcrop/AwvMxLX1xRFrbD2m/trawertyn-na-elewacje-classico-jasny-kamien-naturalny-wloski-mxBZW2bREKCrJNyx.jpeg',
 footerClear:'https://images.unsplash.com/photo-1768200498972-fd56353d73fc?auto=format&fit=crop&q=85&w=2400'
};
const projects=[['01','دار الوادي',IMG.hero],['02','بيت الساحة',IMG.courtyard],['03','دار النور',IMG.desert]];
const heroLetters=['أ','ث','ر'];

function Cursor(){const [p,setP]=useState({x:-100,y:-100});const [mode,setMode]=useState('');const [seen,setSeen]=useState(false);useEffect(()=>{const m=e=>{setSeen(true);setP({x:e.clientX,y:e.clientY})};const o=e=>setMode(e.target.closest('[data-cursor]')?.dataset.cursor||'');window.addEventListener('mousemove',m);window.addEventListener('mouseover',o);return()=>{window.removeEventListener('mousemove',m);window.removeEventListener('mouseover',o)}},[]);return <motion.div className={'cursor '+(seen?'seen ':'')+(mode?'active':'')} animate={{x:p.x-20,y:p.y-20}} transition={{type:'spring',damping:28,stiffness:450,mass:.2}}><i/><b>{mode}</b></motion.div>}
function Nav(){const [menuOpen,setMenuOpen]=useState(false);return <><nav><a className="brand">أثــر</a><button className="menu-trigger" data-cursor={menuOpen?'إغلاق':'فتح'} onClick={()=>setMenuOpen(v=>!v)}><span>{menuOpen?'×':'＋'}</span> القائمة</button></nav><AnimatePresence>{menuOpen&&<motion.div className="menu-overlay" initial={{clipPath:'inset(0 0 100% 0)'}} animate={{clipPath:'inset(0 0 0% 0)'}} exit={{clipPath:'inset(0 0 100% 0)'}} transition={{duration:.7,ease:[.76,0,.24,1]}}><div className="menu-grid"/><div className="menu-ghost">أثر</div><div className="menu-links">{['المشاريع','الاستوديو','المنهج','تواصل معنا'].map((x,i)=><motion.a key={x} href="#" data-cursor="↗" initial={{y:80,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:.18+i*.08,duration:.6}}><span>٠{i+1}</span>{x}<i>↗</i></motion.a>)}</div><p className="menu-note">عمارة تُقرأ بالحركة، والضوء، والفراغ.</p></motion.div>}</AnimatePresence></>}
function Hero(){const ref=useRef();const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']});const scale=useTransform(scrollYProgress,[0,1],[1,1.14]);const typeY=useTransform(scrollYProgress,[0,1],['0%','-18%']);return <section className="hero" ref={ref}><motion.div className="hero-media" style={{scale,backgroundImage:`url(${IMG.hero})`}}/><div className="hero-grid"/><motion.div className="hero-type" style={{y:typeY}}><h1 aria-label="أثر">{heroLetters.map((l,i)=><motion.span className="hero-letter" key={i} initial={{opacity:0,y:'70%',rotate:5}} animate={{opacity:1,y:0,rotate:0}} transition={{delay:.2+i*.16,duration:.9,ease:[.16,1,.3,1]}}>{l}</motion.span>)}</h1><div className="hero-line"><p>نرسم الفراغ<br/>قبل أن نبنيه.</p></div></motion.div><div className="scrollmark"><span>↓</span> اسحب المشهد</div></section>}
function SketchAlive(){return <div className="sketch-alive" data-cursor="راقب"><div className="sketch-photo"><img src={IMG.realSketch} alt="يد ترسم مخططاً معمارياً بالقلم على ورق شفاف"/><motion.div className="trace-line" animate={{scaleX:[0,.3,.72,1],opacity:[0,1,1,0]}} transition={{duration:4.8,repeat:Infinity,ease:'easeInOut'}}/></div><span className="sketch-caption">رسم حقيقي، طبقات من ورق الشف، وقرار يتكوّن باليد.</span></div>}
function Instrument(){return <section className="instrument"><SketchAlive/><div className="instrument-copy"><h2>من الخط<br/>إلى المكان.</h2><p>كل خط قرار. كل فراغ علاقة. وكل انتقال في هذه الصفحة جزء من الحكاية.</p></div></section>}
function ProjectScene({p}){return <article className="project-scene"><div className="project-bg" style={{backgroundImage:`url(${p[2]})`}}/><div className="project-shade"/><div className="project-name"><h3>{p[1]}</h3></div><button className="project-cta" data-cursor="↗">شاهد المشروع <span>↗</span></button><div className="project-outline">{p[0]}</div></article>}
function Projects(){const ref=useRef();const {scrollYProgress}=useScroll({target:ref});const x=useTransform(scrollYProgress,[0,1],['0%','-66.666%']);return <section className="projects" ref={ref}><div className="sticky"><motion.div className="project-track" style={{x}}>{projects.map(p=><ProjectScene p={p} key={p[0]}/>)}</motion.div></div></section>}
function Words(){const [active,setActive]=useState(0);const words=[['الضوء',IMG.light],['الظل',IMG.shadow],['المادة',IMG.material]];return <section className="words"><motion.div key={active} className="words-bg" initial={{opacity:0,scale:1.06}} animate={{opacity:.72,scale:1}} transition={{duration:.7}} style={{backgroundImage:`url(${words[active][1]})`}}/><div className="words-intro"><h2>الضوء والظل والمادة</h2><p>ثلاثة عناصر تغيّر إحساسنا بالمكان: الضوء يكشف الكتلة، الظل يرسم العمق، والمادة تمنح الفراغ ملمسه وذاكرته.</p></div><div className="word-list">{words.map((w,i)=><button onMouseEnter={()=>setActive(i)} className={active===i?'on':''} key={w[0]} data-cursor="عرض">{w[0]}<i>↗</i></button>)}</div></section>}
function Passage(){const ref=useRef();const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const clip=useTransform(scrollYProgress,[.08,.48],['inset(18% 47% 18% 47%)','inset(0% 0% 0% 0%)']);const x=useTransform(scrollYProgress,[0,.65],['10%','-8%']);return <section className="passage" ref={ref}><div className="passage-base" style={{backgroundImage:`url(${IMG.plan})`}}/><motion.div className="passage-photo" style={{clipPath:clip,backgroundImage:`url(${IMG.house})`}}/><motion.h2 style={{x}}>بين<br/>الداخل<br/>والخارج.</motion.h2><div className="passage-line"/><p>خط واحد يتحوّل إلى حدّ، ثم إلى فتحة، ثم يختفي داخل الضوء.</p></section>}
function Fragments(){const ref=useRef();const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const x1=useTransform(scrollYProgress,[0,1],['-8%','18%']);const x2=useTransform(scrollYProgress,[0,1],['14%','-15%']);return <section className="fragments" ref={ref}><div className="fragment-title"><h2>المشهد<br/>لا يقف ساكناً.</h2><p>لقطات، خامات، خطوط، وظلال تتحرك بسرعات مختلفة لتبني إيقاعاً واحداً.</p></div><motion.div className="film-row row-one" style={{x:x1}}>{[IMG.courtyard,IMG.material,IMG.desert,IMG.plan].map((im,i)=><div className="film" key={i}><img src={im}/></div>)}</motion.div><motion.div className="film-row row-two" style={{x:x2}}>{[IMG.hero,IMG.house,IMG.light].map((im,i)=><div className="film wide" key={i}><img src={im}/></div>)}</motion.div><div className="fragment-rail">أثر — ضوء — كتلة — فراغ — أثر — ضوء — كتلة — فراغ</div></section>}
function End(){return <section className="end"><div className="end-image" style={{backgroundImage:`url(${IMG.footerClear})`}}/><div className="end-copy"><h2>المكان<br/>يترك أثراً.</h2></div><div className="end-links"><a href="#" data-cursor="↗">مشاهدة المشاريع ↗</a><a href="#" data-cursor="↗">تواصل معنا ↗</a></div></section>}
function App(){return <><Cursor/><Nav/><main><Hero/><Instrument/><Projects/><Words/><Passage/><Fragments/><End/></main></>}
createRoot(document.getElementById('root')).render(<App/>);
