import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AnimatePresence,motion,useScroll,useTransform} from 'framer-motion';
import './styles.css';

const IMG={
 hero:'https://mavilongevity.com/images/properties/mavi-r3-50.jpg',
 courtyard:'https://static.spacecrafted.com/fa3c03d2f10d42bfb8bfdd0889cf1089/i/e9f952ad1909484ea69dcb9385c7b0ee/1/GCuCv726gZycFxatRCb7iU/ES11.jpg',
 plan:'https://vtsland.ir/wp-content/uploads/2022/05/villa-plan-design.jpg',
 house:'https://images.divisare.com/images/f_auto%2Cq_auto%2Cw_auto/v1627307021/llnyyh02bhiawbk3cxtx/grupo-studio-gonzalo-viramonte-casa-si.jpg',
 desert:'https://morphome.app/assets/renders/concrete-desert-house.jpg',
 light:'https://www.mlarquitectura.cat/wp-content/uploads/2024/05/2020-07-31-09.41.21-scaled.jpg',
 shadow:'https://images.divisare.com/images/c_limit%2Cf_auto%2Ch_2000%2Cq_auto%2Cw_3000/v1468257182/w72llzpljwrj1rrxdjsw/bernardo-rosello-ramiro-sosa-house-in-palihue.jpg',
 material:'https://assets.zyrosite.com/cdn-cgi/image/format%3Dauto%2Cw%3D1600%2Ch%3D1600%2Cfit%3Dcrop/AwvMxLX1xRFrbD2m/trawertyn-na-elewacje-classico-jasny-kamien-naturalny-wloski-mxBZW2bREKCrJNyx.jpeg',
 sky:'/assets/sky.png',
 building:'/assets/building-v7.png',
 compareSketch:'/assets/compare-sketch.png',
 compareRender:'/assets/compare-render.png'
};
const projects=[['01','دار الوادي',IMG.hero],['02','بيت الساحة',IMG.courtyard],['03','دار النور',IMG.desert]];
const HERO_VIDEO='https://videos.pexels.com/video-files/38675652/16428547_3840_2160_30fps.mp4';

function Cursor(){const [p,setP]=useState({x:-100,y:-100});const [mode,setMode]=useState('');const [seen,setSeen]=useState(false);useEffect(()=>{const m=e=>{setSeen(true);setP({x:e.clientX,y:e.clientY})};const o=e=>setMode(e.target.closest('[data-cursor]')?.dataset.cursor||'');window.addEventListener('mousemove',m);window.addEventListener('mouseover',o);return()=>{window.removeEventListener('mousemove',m);window.removeEventListener('mouseover',o)}},[]);return <motion.div className={'cursor '+(seen?'seen ':'')+(mode?'active':'')} animate={{x:p.x-20,y:p.y-20}} transition={{type:'spring',damping:28,stiffness:450,mass:.2}}><i/><b>{mode}</b></motion.div>}
function Nav(){const [menuOpen,setMenuOpen]=useState(false);const [scrolled,setScrolled]=useState(false);useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>72);onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);return <><nav className={scrolled?'scrolled':''}><a className="brand">أثــر</a><button className="menu-trigger" data-cursor={menuOpen?'إغلاق':'فتح'} onClick={()=>setMenuOpen(v=>!v)}><span>{menuOpen?'×':'＋'}</span> القائمة</button></nav><AnimatePresence>{menuOpen&&<motion.div className="menu-overlay" initial={{clipPath:'inset(0 0 100% 0)'}} animate={{clipPath:'inset(0 0 0% 0)'}} exit={{clipPath:'inset(0 0 100% 0)'}} transition={{duration:.7,ease:[.76,0,.24,1]}}><div className="menu-grid"/><div className="menu-ghost">أثر</div><div className="menu-links">{['المشاريع','الاستوديو','المنهج','تواصل معنا'].map((x,i)=><motion.a key={x} href="#" data-cursor="↗" initial={{y:80,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:.18+i*.08,duration:.6}}><span>٠{i+1}</span>{x}<i>↗</i></motion.a>)}</div><p className="menu-note">عمارة تُقرأ بالحركة، والضوء، والفراغ.</p></motion.div>}</AnimatePresence></>}
function Hero(){const ref=useRef();const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']});const scale=useTransform(scrollYProgress,[0,1],[1,1.06]);const typeY=useTransform(scrollYProgress,[0,1],['0%','-10%']);const blinds=Array.from({length:9});return <section className="hero" ref={ref}><motion.video className="hero-video" autoPlay muted loop playsInline src={HERO_VIDEO} style={{scale}} initial={{opacity:0}} animate={{opacity:1}} transition={{duration:2.1,delay:.1,ease:'easeOut'}}/><motion.div className="hero-darkness" initial={{opacity:1}} animate={{opacity:0}} transition={{duration:2.4,ease:[.4,0,.2,1]}}/><div className="hero-grid"/><motion.div className="hero-type" style={{y:typeY}}><div className="hero-word" aria-label="أثر">{blinds.map((_,i)=><motion.span aria-hidden="true" className="blind-slice" key={i} style={{clipPath:`inset(${i*11.111}% 0 ${100-(i+1)*11.111}% 0)`}} initial={{x:i%2===0?'10%':'-10%',opacity:0}} animate={{x:'0%',opacity:1}} transition={{delay:.35+i*.055,duration:.85,ease:[.16,1,.3,1]}}>أثر</motion.span>)}</div><div className="hero-line"><p>نرسم الفراغ<br/>قبل أن نبنيه.</p></div></motion.div></section>}
function LineToSpace(){const ref=useRef();const [reveal,setReveal]=useState(34);const move=e=>{const r=ref.current?.getBoundingClientRect();if(!r)return;setReveal(Math.max(7,Math.min(100,((e.clientX-r.left)/r.width)*100)))};return <motion.div ref={ref} className="line-space" data-cursor="حرّك" initial={{x:'-16%',opacity:0}} whileInView={{x:0,opacity:1}} viewport={{once:true,amount:.25}} transition={{duration:1,ease:[.16,1,.3,1]}} onPointerMove={move}><div className="line-space-base"/><div className="line-space-photo" style={{clipPath:`inset(0 ${100-reveal}% 0 0)`,backgroundImage:`url(${IMG.house})`}}/><div className="line-space-rule" style={{left:`${reveal}%`}}><i/></div><span className="line-space-note">حرّك الخط ليظهر المكان</span></motion.div>}
function Instrument(){return <section className="instrument"><LineToSpace/><motion.div className="instrument-copy" initial={{x:'18%',opacity:0}} whileInView={{x:0,opacity:1}} viewport={{once:true,amount:.3}} transition={{duration:1.05,ease:[.16,1,.3,1]}}><h2>من الخط<br/>إلى المكان.</h2><p>كل خط قرار. كل فراغ علاقة. وكل انتقال في هذه الصفحة جزء من الحكاية.</p></motion.div></section>}
function ProjectScene({p}){return <article className="project-scene"><div className="project-bg" style={{backgroundImage:`url(${p[2]})`}}/><div className="project-shade"/><div className="project-name"><h3>{p[1]}</h3></div><button className="project-cta" data-cursor="↗">شاهد المشروع <span>↗</span></button><div className="project-outline">{p[0]}</div></article>}
function Projects(){const ref=useRef();const {scrollYProgress}=useScroll({target:ref});const x=useTransform(scrollYProgress,[0,1],['0%','-66.666%']);return <section className="projects" ref={ref}><div className="sticky"><motion.div className="project-track" style={{x}}>{projects.map(p=><ProjectScene p={p} key={p[0]}/>)}</motion.div></div></section>}
function Words(){const [active,setActive]=useState(0);const words=[['الضوء',IMG.light],['الظل',IMG.shadow],['المادة',IMG.material]];return <section className="words"><motion.div key={active} className="words-bg" initial={{opacity:0,scale:1.06}} animate={{opacity:.72,scale:1}} transition={{duration:.7}} style={{backgroundImage:`url(${words[active][1]})`}}/><div className="words-intro"><h2>الضوء والظل والمادة</h2><p>ثلاثة عناصر تغيّر إحساسنا بالمكان: الضوء يكشف الكتلة، الظل يرسم العمق، والمادة تمنح الفراغ ملمسه وذاكرته.</p></div><div className="word-list">{words.map((w,i)=><button onMouseEnter={()=>setActive(i)} className={active===i?'on':''} key={w[0]} data-cursor="عرض">{w[0]}<i>↗</i></button>)}</div></section>}
function Passage(){const ref=useRef();const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const clip=useTransform(scrollYProgress,[.08,.48],['inset(18% 47% 18% 47%)','inset(0% 0% 0% 0%)']);const x=useTransform(scrollYProgress,[0,.65],['10%','-8%']);return <section className="passage" ref={ref}><div className="passage-base" style={{backgroundImage:`url(${IMG.plan})`}}/><motion.div className="passage-photo" style={{clipPath:clip,backgroundImage:`url(${IMG.house})`}}/><motion.h2 style={{x}}>بين<br/>الداخل<br/>والخارج.</motion.h2><div className="passage-line"/><p>خط واحد يتحوّل إلى حدّ، ثم إلى فتحة، ثم يختفي داخل الضوء.</p></section>}
function Fragments(){const ref=useRef();const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const x1=useTransform(scrollYProgress,[0,1],['-8%','18%']);const x2=useTransform(scrollYProgress,[0,1],['14%','-15%']);return <section className="fragments" ref={ref}><div className="fragment-title"><h2>المشهد<br/>لا يقف ساكناً.</h2><p>لقطات، خامات، خطوط، وظلال تتحرك بسرعات مختلفة لتبني إيقاعاً واحداً.</p></div><motion.div className="film-row row-one" style={{x:x1}}>{[IMG.courtyard,IMG.material,IMG.desert,IMG.plan].map((im,i)=><div className="film" key={i}><img src={im}/></div>)}</motion.div><motion.div className="film-row row-two" style={{x:x2}}>{[IMG.hero,IMG.house,IMG.courtyard].map((im,i)=><div className="film wide" key={i}><img src={im}/></div>)}</motion.div><div className="fragment-rail">أثر — ضوء — كتلة — فراغ — أثر — ضوء — كتلة — فراغ</div></section>}
function PlanToSpace(){const ref=useRef();const [split,setSplit]=useState(52);const move=e=>{const r=ref.current?.getBoundingClientRect();if(!r)return;setSplit(Math.max(8,Math.min(92,((e.clientX-r.left)/r.width)*100)))};return <section className="compare-section"><div className="compare-copy"><h2>من المسقط<br/>إلى المشهد.</h2><p>اسحب الخط لترى كيف تتحوّل الفكرة المرسومة إلى فراغ يمكن العيش داخله.</p></div><div ref={ref} className="compare-stage" onPointerMove={e=>e.buttons&&move(e)} onPointerDown={move} data-cursor="اسحب"><div className="compare-built" style={{backgroundImage:`url(${IMG.compareRender})`}}/><div className="compare-plan" style={{clipPath:`inset(0 ${100-split}% 0 0)`,backgroundImage:`url(${IMG.compareSketch})`}}/><div className="compare-handle" style={{left:`${split}%`}}><span>↔</span></div><div className="compare-label plan-label">المسقط</div><div className="compare-label built-label">المشهد</div></div></section>}
function End(){const ref=useRef();const {scrollYProgress}=useScroll({target:ref,offset:['start 92%','start 22%']});const buildingY=useTransform(scrollYProgress,[0,1],['62%','0%']);const buildingScale=useTransform(scrollYProgress,[0,1],[.96,1]);const copyY=useTransform(scrollYProgress,[0,1],['8%','0%']);return <section className="end" ref={ref}><img className="end-sky-img" src={IMG.sky} alt=""/><motion.img className="end-building" src={IMG.building} alt="" style={{y:buildingY,scale:buildingScale}}/><motion.div className="end-copy" style={{y:copyY}}><h2>المكان<br/>يترك أثراً.</h2></motion.div><div className="end-links"><a href="#" data-cursor="↗">مشاهدة المشاريع ↗</a><a href="#" data-cursor="↗">تواصل معنا ↗</a></div></section>}
function App(){return <><Cursor/><Nav/><main><Hero/><Instrument/><Projects/><Words/><Passage/><Fragments/><PlanToSpace/><End/></main></>}
createRoot(document.getElementById('root')).render(<App/>);
