import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,useScroll,useTransform} from 'framer-motion';
import './styles.css';

const IMG={
 hero:'https://mavilongevity.com/images/properties/mavi-r3-50.jpg',
 courtyard:'https://static.spacecrafted.com/fa3c03d2f10d42bfb8bfdd0889cf1089/i/e9f952ad1909484ea69dcb9385c7b0ee/1/GCuCv726gZycFxatRCb7iU/ES11.jpg',
 plan:'https://vtsland.ir/wp-content/uploads/2022/05/villa-plan-design.jpg',
 model:'https://hoffmann-am.com/hs-fs/hubfs/Haus.png?height=1024&name=Haus.png&width=1536',
 house:'https://images.divisare.com/images/f_auto%2Cq_auto%2Cw_auto/v1627307021/llnyyh02bhiawbk3cxtx/grupo-studio-gonzalo-viramonte-casa-si.jpg',
 desert:'https://morphome.app/assets/renders/concrete-desert-house.jpg'
};
const projects=[['01','دار الوادي',IMG.hero],['02','بيت الساحة',IMG.courtyard],['03','دار النور',IMG.desert]];

function Cursor(){const [p,setP]=useState({x:-100,y:-100});const [mode,setMode]=useState('');useEffect(()=>{const m=e=>setP({x:e.clientX,y:e.clientY});const o=e=>setMode(e.target.closest('[data-cursor]')?.dataset.cursor||'');window.addEventListener('mousemove',m);window.addEventListener('mouseover',o);return()=>{window.removeEventListener('mousemove',m);window.removeEventListener('mouseover',o)}},[]);return <motion.div className={'cursor '+(mode?'active':'')} animate={{x:p.x-20,y:p.y-20}} transition={{type:'spring',damping:28,stiffness:450,mass:.2}}><i/><b>{mode}</b></motion.div>}
function Nav(){return <nav><a className="brand">أثــر</a><div className="nav-index">A—01 / 26</div><button data-cursor="فتح">القائمة <span>＋</span></button></nav>}
function Hero(){const ref=useRef();const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']});const scale=useTransform(scrollYProgress,[0,1],[1,1.32]);const y=useTransform(scrollYProgress,[0,1],['0%','18%']);const typeY=useTransform(scrollYProgress,[0,1],['0%','-45%']);return <section className="hero" ref={ref}><motion.div className="hero-media" style={{scale,y,backgroundImage:`url(${IMG.hero})`}}/><div className="hero-grid"/><motion.div className="hero-type" style={{y:typeY}}><span className="micro">ARCHITECTURE / SPACE / LIGHT</span><h1>أثـــــر</h1><div className="hero-line"><p>نرسم الفراغ<br/>قبل أن نبنيه.</p><span>24° 42′ N<br/>46° 40′ E</span></div></motion.div><div className="scrollmark"><span>↓</span> اسحب المشهد</div><div className="measure m1">12.40 M</div><div className="measure m2">A—A</div></section>}
function Instrument(){const ref=useRef();const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const r=useTransform(scrollYProgress,[0,1],[-8,7]);const x=useTransform(scrollYProgress,[0,1],['8%','-10%']);return <section className="instrument" ref={ref}><div className="section-index">01 — PROCESS / أثر</div><motion.div className="plan-sheet" style={{rotate:r,x}} data-cursor="اسحب"><img src={IMG.plan}/><span>GROUND / 01</span></motion.div><motion.div className="photo-sheet" drag dragConstraints={{left:-100,right:100,top:-60,bottom:60}} whileDrag={{scale:1.03}} data-cursor="اسحب"><img src={IMG.courtyard}/><b>COURTYARD<br/>STUDY</b></motion.div><div className="instrument-copy"><div className="kicker">من الخط إلى المكان</div><h2>الفكرة لا تبدأ<br/><em>بالصورة.</em></h2><p>كل خط قرار. كل فراغ علاقة. وكل انتقال في هذه الصفحة جزء من الحكاية.</p></div><svg className="diagram" viewBox="0 0 400 400"><circle cx="200" cy="200" r="130"/><circle cx="200" cy="200" r="82"/><path d="M20 200H380M200 20V380M70 70L330 330"/></svg></section>}
function ProjectScene({p,i}){return <article className="project-scene"><div className="project-bg" style={{backgroundImage:`url(${p[2]})`}}/><div className="project-shade"/><div className="project-top"><span>{p[0]} / 03</span><span>SELECTED RESIDENCE</span></div><div className="project-name"><small>PROJECT — {p[0]}</small><h3>{p[1]}</h3></div><div className="project-meta">ARCH / 2026<br/>PRIVATE HOUSE<br/>VIEW PROJECT ↗</div><div className="project-outline">{p[0]}</div></article>}
function Projects(){const ref=useRef();const {scrollYProgress}=useScroll({target:ref});const x=useTransform(scrollYProgress,[0,1],['0%','-66.666%']);return <section className="projects" ref={ref}><div className="sticky"><motion.div className="project-track" style={{x}}>{projects.map((p,i)=><ProjectScene p={p} i={i} key={p[0]}/>)}</motion.div></div></section>}
function Words(){const [active,setActive]=useState(0);const words=[['الضوء',IMG.courtyard,'LIGHT / 01'],['الظل',IMG.house,'SHADOW / 02'],['المادة',IMG.model,'MATTER / 03']];return <section className="words"><motion.div key={active} className="words-bg" initial={{opacity:0,scale:1.08}} animate={{opacity:.58,scale:1}} transition={{duration:.7}} style={{backgroundImage:`url(${words[active][1]})`}}/><div className="words-note">THREE ELEMENTS / ONE SPACE</div><div className="word-list">{words.map((w,i)=><button onMouseEnter={()=>setActive(i)} className={active===i?'on':''} key={w[0]} data-cursor="عرض"><span>{w[2]}</span>{w[0]}<i>↗</i></button>)}</div><div className="orb"/></section>}
function ModelScene(){return <section className="model-scene"><div className="model-head"><span>02 — SPATIAL STUDY</span><h2>فكّك<br/>المشهد.</h2></div><div className="layers" data-cursor="حرّك"><motion.div whileHover={{x:-50,y:-25,rotate:-4}} className="layer l1"><img src={IMG.model}/></motion.div><motion.div whileHover={{x:45,y:20,rotate:5}} className="layer l2"><img src={IMG.plan}/></motion.div><motion.div whileHover={{x:-25,y:45,rotate:-2}} className="layer l3"><img src={IMG.desert}/></motion.div></div><div className="model-caption">EXPLODED VIEW<br/>01—03<br/><br/>مرّر المؤشر لتفكيك الطبقات</div></section>}
function Archive(){return <section className="archive"><div className="archive-title"><span>ARCHIVE / 06</span><h2>تفاصيل<br/>تتحرك.</h2></div>{[IMG.hero,IMG.plan,IMG.house,IMG.model,IMG.courtyard].map((im,i)=><motion.div key={i} className={'archive-img a'+i} drag dragElastic={.2} whileHover={{scale:1.05,zIndex:20}} data-cursor="اسحب"><img src={im}/><span>0{i+1} / STUDY</span></motion.div>)}<div className="ticker">أثر — مساحة — ضوء — مادة — حركة — أثر — مساحة — ضوء — مادة — حركة —</div></section>}
function End(){return <section className="end"><div className="end-sky"/><div className="end-image" style={{backgroundImage:`url(${IMG.hero})`}}/><div className="end-copy"><span>ATHAR / 2026</span><h2>المكان<br/>يترك أثراً.</h2><div><p>مشاهدة المشاريع ↗</p><p>تواصل معنا ↗</p></div></div></section>}
function App(){return <><Cursor/><Nav/><main><Hero/><Instrument/><Projects/><Words/><ModelScene/><Archive/><End/></main></>};
createRoot(document.getElementById('root')).render(<App/>);
